cffi: fix compilation with latest version
Remove field that causes build errors with the latest libyang versions:

build/temp.linux-x86_64-cpython-37/_libyang.c:8143:32: error:
initialization of ‘struct hash_table **’ from incompatible pointer type
‘struct ly_ht **’ [-Werror=incompatible-pointer-types]

children_ht is not used anywhere, remove it.

Signed-off-by: Robin Jarry <robin@jarry.cc>