tox: fix dependencies
Since flake8 6.0, the copyright plugin fails to run:

  ValueError: 'int' is not callable

This plugin is not critical, remove it.

Also use latest versions of black and pylint along the way.

Link: https://github.com/savoirfairelinux/flake8-copyright/issues/19
Signed-off-by: Robin Jarry <robin@jarry.cc>