data: fix error when converting float leaf values
Fix the following error:

   libyang/data.py", line 554, in cdata_leaf_value
     return lib.lyd_dec64_to_double(cdata)
 TypeError: initializer for ctype 'struct lyd_node *' must be a pointer
 to same type, not cdata 'struct lyd_node_leaf_list *'

Fixes: 90edc41308bf ("data: optimize DNode.print_dict")
Signed-off-by: Robin Jarry <robin.jarry@6wind.com>