tox: fix lint with python 3.12
Fix the following error when running pylint with python 3.12:

 Exception on node ImportFrom in file 'cffi/build.py'
 Traceback (most recent call last):
   File ".../python3.12/site-packages/pylint/checkers/imports.py", line 846, in _get_imported_module
     return importnode.do_import_module(modname)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File ".../python3.12/site-packages/astroid/nodes/_base_nodes.py", line 146, in do_import_module
     return mymodule.import_module(
            ^^^^^^^^^^^^^^^^^^^^^^^
   File ".../python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 530, in import_module
     return AstroidManager().ast_from_module_name(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File ".../python3.12/site-packages/astroid/manager.py", line 246, in ast_from_module_name
     return self.ast_from_file(found_spec.location, modname, fallback=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File ".../python3.12/site-packages/astroid/manager.py", line 138, in ast_from_file
     return AstroidBuilder(self).file_build(filepath, modname)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File ".../python3.12/site-packages/astroid/builder.py", line 144, in file_build
     module, builder = self._data_build(data, modname, path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File ".../python3.12/site-packages/astroid/builder.py", line 204, in _data_build
     module = builder.visit_module(node, modname, node_file, package)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File ".../python3.12/site-packages/astroid/rebuilder.py", line 254, in visit_module
     [self.visit(child, newnode) for child in node.body],
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File ".../python3.12/site-packages/astroid/rebuilder.py", line 609, in visit
     visit_method = getattr(self, visit_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: 'TreeRebuilder' object has no attribute 'visit_typealias'

Update all lint and format dependencies to their latest stable releases.
Ignore the new use-implicit-booleaness-not-comparison-to-string and
use-implicit-booleaness-not-comparison-to-zero pylint rules. Use the
correct Hashable reference from collections.abc instead of the
deprecated typing alias.

Signed-off-by: Robin Jarry <robin@jarry.cc>