schema: check cdata_parsed before using it
Sometimes, cdata_parsed is None. Check it before using it, as we do in
the other functions using cdata_parsed.

It fixes this error:
AttributeError: 'NoneType' object has no attribute 'range'

Signed-off-by: Samuel Gauthier <samuel.gauthier@6wind.com>