data: add insert_sibling function to DNode
This patch introduce the insert_sibling function usable for inserting
data nodes on the module level.

Add a unit test. A presence container is added on the conf container of
the yolo-nodetypes module to avoid this error:
> libyang.util.LibyangError: failed to parse data tree: Too few "list1" instances.

Fixes: #95
Signed-off-by: Stefan Gula <steweg@gmail.com>
Signed-off-by: Samuel Gauthier <samuel.gauthier@6wind.com>