README: fix data tree example
Fix the following error when running the data tree example provided in
README:

 LibyangError: validation failed: Missing required element "content-id"
 in "yang-library".

When parsing a config tree, we do not have the complete datastore
available (no ietf-yang-library.yang module data).

Link: https://github.com/CESNET/libyang-python/blob/v1.6.1/libyang/schema.py#L154-L155
Link: https://netopeer.liberouter.org/doc/libyang/master/html/group__parseroptions.html
Fixes: f9a930023d67 ("README: update with more examples")
Fixes: #21
Signed-off-by: Robin Jarry <robin.jarry@6wind.com>