cdefs: fix lypy_log_cb prototype
The following error is raised when logging:
> File "/usr/lib/python3/dist-packages/libyang/log.py", line 59, in configure_logging
> TypeError: initializer for ctype 'void(*)(LY_LOG_LEVEL, char *, char *, char *,
>                uint64_t)' must be a pointer to same type, not cdata 'void(*)(LY_LOG_LEVEL, char *, char
>                *)'

Fix lypy_log_cb's prototype.

Fixes: 3849dd523d30 ("Port to libyang3")
Signed-off-by: Jeremie Leska <jeremie.leska@6wind.com>
Signed-off-by: Samuel Gauthier <samuel.gauthier@6wind.com>