schema: add basic support for choice and case
Let's add enough to parse a model with choices and cases, so that
iter_tree is working. Before this patch, the unit test added by this
patch would fail with:

> ======================================================================
> ERROR: test_iter_tree (test_schema.ContainerTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>  File "(...)/libyang-python/tests/test_schema.py", line 278, in test_iter_tree
>    tree = list(self.container.iter_tree())
>  File "(...)/libyang-python/.tox/py3/lib/python3.9/site-packages/libyang/schema.py", line 1148, in iter_tree
>    yield self.new(self.context, n)
>  File "(...)/libyang-python/.tox/py3/lib/python3.9/site-packages/libyang/schema.py", line 1192, in new
>    raise TypeError("node type %s not implemented" % cdata.nodetype)
> TypeError: node type 2 not implemented

Signed-off-by: Samuel Gauthier <samuel.gauthier@6wind.com>