data: return keyed lists in print_dict
When dealing with data tree that contain lists with large number of
elements, accessing specific elements scales in O(n).

Instead of native python lists, use a custom implementation (KeyedList)
which holds information about the actual index of its elements based on
their "key".

The "key" of each element is a tuple of string values of each list key
(in most cases, there is only one key). Here are a few examples:

 >>> l = KeyedList()  # no key name declared: YANG leaf-list
 >>> l.extend(['a', 'b', 'c', 'd'])
 >>> l.index('d')  # done in O(1), regardless of list size
 3
 >>> l.insert_after('b', 'x')  # O(1) as well
 >>> l
 ['a', 'b', 'x', 'c', 'd']

 >>> l = KeyedList(key_name='name')  # key declared: YANG list
 >>> l.append({'name': 'eth0', 'mtu': 1500})  # dict required
 >>> l.append({'mtu': 1280})  # XXX: key required
 KeyError: 'name'
 >>> l.append({'name': 'eth0', 'mtu': 1280})  # no duplicates allowed
 ValueError: element already in list
 >>> l.append({'name': 'eth2', 'mtu': 1280})
 >>> l.index('eth2')  # O(1) as well
 1
 >>> l.insert_after('eth0', {'name': 'eth1', 'mtu': 1400})
 >>> l
 [{'name': 'eth0', 'mtu': 1500}, {'name': 'eth1', 'mtu': 1400},
 {'name': 'eth2', 'mtu': 1280}]

 >>> l = KeyedList(key_name=('ip', 'port'))  # multiple keys
 >>> l.append({'ip': '1.1.1.1', 'port': 80})
 >>> l.append({'ip': '2.2.2.2'})  # XXX: all keys are required
 KeyError: 'port'
 >>> l.append({'ip': '1.1.1.1', 'port': 443})
 >>> l.index(('1.1.1.1', '80'))  # O(1) as well
 0
 >>> l.insert_after(('1.1.1.1', '80'), {'ip': '2.2.2.2', 'port': 8080})
 >>> l
 [{'ip': '1.1.1.1', 'port': 80}, {'ip': '2.2.2.2', 'port': 8080},
 {'ip': '1.1.1.1', 'port': 443}]

This feature will be used in the next commits that will add xpath
manipulation for data dictionaries (add, del, move, etc.).

Signed-off-by: Robin Jarry <robin.jarry@6wind.com>