schema: fix type extensions
The ext_size field has been removed, we need to use LY_ARRAY_COUNT now.
It fixes the following error when calling type.extensions():

> File "/(...)/.venv/src/libyang/libyang/schema.py", line 579, in extensions
>   for i in range(self.cdata.ext_size):
> AttributeError: cdata 'struct lysc_type *' has no field 'ext_size'

Signed-off-by: Samuel Gauthier <samuel.gauthier@6wind.com>